name: BUILD CUSTOM PACKAGES
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: INSTALL DEPENDENCIES & SETUP XBPS
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support wget liblz4-tool xz-utils proot

          wget https://repo-default.voidlinux.org/static/xbps-static-latest.aarch64-musl.tar.xz
          mkdir xbps
          tar xvf xbps-static-latest.aarch64-musl.tar.xz -C xbps
          sudo cp xbps/usr/bin/xbps-* /usr/bin/

      - name: BUILD PACKAGES
        run: |
          #echo "XBPS_CHROOT_CMD=proot" >> etc/conf
          ./xbps-src binary-bootstrap
          ./xbps-src pkg kalium-base-files
          ./xbps-src pkg kalium-base-system

      - name: CREATE LOCAL REPO INDEX
        run: |
          xbps-rindex -a hostdir/binpkgs/*.xbps

      - name: UPLOAD REPO AS ARTIFACT
        uses: actions/upload-artifact@v4
        with:
          name: kalium-binpkgs
          path: hostdir/binpkgs/
